### ISSUE TITLE
Team page

### ISSUE THREAD

**Issue by jobolin** [Kenshii/Dribbble-Bot#2]
How can I set this up for a team page? Im trying to redirect to the team page after login using something like: 

`print('Location:https://dribbble.com/sessions/TEAMPAGE/switch')`

But it appears that dribble doesnt like the URL and any authentication steps I try makes the script fail

**Comment by jobolin** [comment]
It looks like you cant go to the URL directly, instead the bot needs to post https://dribbble.com/sessions/TEAMPAGE/switch some time after login

**Comment by jobolin** [comment]
@Kenshii any ideas?

**Comment by Kenshii** [comment]
I don't know much about Dribbble. I basically just made the bot and deleted my account.
What exactly are you looking for it to do?
I don't really understand what you're looking for.
